version: "3.9"

services:
  app:
    build: .
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - friday-poker-network
  mongo:
    image: mongo:7.0.28
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /srv/mongodb:/data/db
      - /srv/mongodb-keyfile:/etc/mongo-keyfile:ro

    command: >
      mongod
      --replSet rs0
      --bind_ip_all
      --auth
      --keyFile /etc/mongo-keyfile
    networks:
      - friday-poker-network
networks:
  friday-poker-network:
    driver: bridge
